version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgreadmin
      - POSTGRES_DB=CatalogDb
    restart: always
    ports: 
        - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/  
  
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgreadmin
      - POSTGRES_DB=BasketDb
    restart: always
    ports: 
        - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/  

  distribuitedcache:
    container_name: distribuitedcache
    restart: always
    ports:
     - "6379:6379"
  
  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Sw12345678 
    restart: always
    ports:
     - "1433:1433"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__connStr=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgreadmin;Include Error Detail=true
    depends_on:         
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__connStr=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgreadmin;Include Error Detail=true
      - ConnectionStrings__Redis=distribuitedcache:6379     
    depends_on:                                             
      - basketdb
      - distribuitedcache
    ports:                                          
      - "6001:8080"                                      
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__GrpcConnStr=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
