version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgreadmin
      - POSTGRES_DB=CatalogDb
    restart: always
    ports: 
        - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/  
  
  
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__connStr=Server=catalogdb;Port=5433;Database=CatalogDb;User Id=postgres;Password=postgreadmin;Include Error Detail=true
    depends_on:         #il doppio trattino serve a sovrascrivere la string di connessione esistente (nell'appsettings)      
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
